Add coach 1
aichner/KISy-Firebase pull request #1
Opened 2020-04-14 23:06 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- The current web app has no functionality.

**What is the new behavior (if this is a feature change)?**
- Cats can now be created.

**Other information**:
- The version has been updated to 1.0.0

2020-04-14 23:14 UTC, Aichnerc reviewed
Looks good enough for v.1.0.0 - 🔥👀

2020-04-14 23:20 UTC, kleberbaum commented
> **Checklist:**
> 
> * [x]  Have you added an explanation of what your changes do and why you'd like them to be included?
> * [ ]  Have you updated or added documentation for the change?
> * [x]  Have you tested your changes with successful results?
> 
> **Type of Changes:**
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  Breaking change (fix or feature that would cause existing functionality to change)
> 
> **What is the current behavior? (link to any open issues here)**
> 
> * The current web app has no functionality.
> 
> **What is the new behavior (if this is a feature change)?**
> 
> * Cats can now be created.
> 
> **Other information**:
> 
> * The version has been updated to 1.0.0

There should be at least a few linked issues.

2020-04-14 23:24 UTC, sweggerat approved these changes
Copyright dates may be updated

2020-04-15 00:11 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/molecules/charts/ResultChart/index.jsx
>          beforeInit: function (chart) {
Please fix false indentation. (2 spaces)

2020-04-15 00:11 UTC, kleberbaum commented on src/components/molecules/charts/ResultChart/index.jsx
> +      Object.keys(this.props.data).map((keyName, i) => {
Please fix false indentation. (2 spaces)

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +          : 0);
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      const facebook_avg = this.getSum(facebook) / analysis.facebook.length;
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      const instagram_avg = this.getSum(instagram) / analysis.instagram.length;
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      const image_avg = this.getSum(image) / analysis.image.length;
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +      };
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/components/organisms/FormCat/index.jsx
> +    const { auth, profile, catDetails } = this.props;
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/index.scss
>   * SPDX-License-Identifier: (EUPL-1.2)
Update to (c) 2020.

2020-04-15 00:11 UTC, kleberbaum commented on src/store/actions/postActions.js
>   */
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/store/actions/userActions.js
>   */
Please add a newline.

2020-04-15 00:11 UTC, kleberbaum commented on src/utilities/_base.scss
>  .btn{
Please fix false indentation. (2 spaces)

2020-04-15 07:54 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +          : 0);
The VSCode Prettier does not like a new line.

2020-04-15 07:55 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 07:55 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +    const { auth, profile, catDetails } = this.props;
The VSCode Prettier does not like a new line.

2020-04-15 07:55 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      const facebook_avg = this.getSum(facebook) / analysis.facebook.length;
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      const instagram_avg = this.getSum(instagram) / analysis.instagram.length;
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      const image_avg = this.getSum(image) / analysis.image.length;
The VSCode Prettier does not like a new line.

2020-04-15 07:56 UTC, Aichnerc commented on src/components/organisms/FormCat/index.jsx
> +      };
The VSCode Prettier does not like a new line.

2020-04-15 22:26 UTC, merged