Improve analysis 1
aichner/KISy-Firebase pull request #2
Opened 2020-04-26 20:23 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, you can not create `zombies` out of `cats`.
- Currently, the image of the user does not load properly.
- Currently, the radar chart for the analysis looks not that great.
- Currently, the dashboard is quite clumpy.

**What is the new behavior (if this is a feature change)?**
- You can now promote `cats` to `zombies`.
- The image has been added to Firestore and is now loaded, including `lazy loading` the image.
- The analysis radar chart has been improved and now looks like its counterpart on the website. Ref: [www.aichner-christian.com](www.aichner-christian.com)
- The dashboard has been seperated into multiple phases to clear up the view.

**Other information**:
- The version has been updated to v1.2.0.

2020-04-26 20:27 UTC, LucaAllmaier commented on src/App.js
>   * Copyright © 2019 Werbeagentur Christian Aichner
missing -2020

2020-04-26 20:28 UTC, LucaAllmaier commented on src/Routes.js
>   * Copyright © 2019 Werbeagentur Christian Aichner
missing -2020

2020-04-26 20:38 UTC, LucaAllmaier commented on src/components/organisms/ZombieList/index.jsx
> +  console.log(state);
is this still needed?

2020-04-26 20:45 UTC, LucaAllmaier reviewed
Looks good.

2020-04-27 08:39 UTC, sweggerat approved these changes
looks good to me

2020-04-27 09:02 UTC, LucaAllmaier approved these changes
Looks good to merge.

2020-04-27 10:04 UTC, schettn requested changes
I would suggest to add a new line.

2020-04-27 10:04 UTC, schettn commented on src/components/molecules/charts/ResultChart/index.jsx
> +        console.log(keyName);
Add new line after the console log or remove the log.

2020-04-27 10:04 UTC, schettn commented on src/components/molecules/charts/ResultChart/index.jsx
> +      const orderedData = {};
add newline

2020-04-27 10:04 UTC, schettn commented on src/components/molecules/modals/AboutUs/index.jsx
> +    let modalNumber = "modal" + nr;
add newline

2020-04-27 10:04 UTC, schettn commented on src/components/organisms/CatList/index.jsx
> +    };
add newline

2020-04-27 10:04 UTC, schettn commented on src/components/molecules/modals/AboutUs/index.jsx
> +  toggle = (nr) => () => {
Is this useful? I would suggest changing it to:
foo = (param) => {}

2020-04-27 10:04 UTC, schettn commented on src/components/organisms/ZombieList/index.jsx
> +    };
add newline

2020-04-27 10:04 UTC, schettn commented on src/components/organisms/ZombieList/index.jsx
> +    const { auth, profile, zombies } = this.props;
Add newline or remove the console log below.

2020-04-27 10:04 UTC, schettn commented on src/components/pages/MessagePage/index.jsx
>      const { auth, profile } = this.props;
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/components/pages/ProfilePage/index.jsx
>      let selected = null;
add newline or remove the console log below

2020-04-27 10:04 UTC, schettn commented on src/components/pages/ProfilePage/index.jsx
>      console.log(curHr);
add newline

2020-04-27 10:04 UTC, schettn commented on src/config/fbInit.js
>  firebase.initializeApp(config);
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        dispatch({ type: "CREATION_SUCCESS", newPost });
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        dispatch({ type: "LIKE_SUCCESS", id });
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        dispatch({ type: "UNLIKE_SUCCESS", id });
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +          dispatch({ type: "REMOVE_SUCCESS", id: post.id });
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +    const firestore = getFirestore();
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        let results = [];
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +          let data = doc.data();
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        localComments = [];
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +      localComments = [];
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        dispatch({ type: "COMMENT_SUCCESS", postId });
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +    const firestore = getFirestore();
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +        let results = [];
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/postActions.js
> +          let data = doc.data();
add newline

2020-04-27 10:04 UTC, schettn commented on src/store/actions/userActions.js
> +          console.log("User no longer exists!");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/actions/userActions.js
> +          console.log("Document data:", doc.data());
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.log("Zombies received");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.log("Can not get zombies", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.log("Cat upgraded");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.log("Can not upgrade cat", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/authReducer.js
>        console.log("Can not disable cat", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Creation success");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Creation error", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Post is spam", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Loading success");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Loading...");
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Loading error", action.err);
add newline or remove the console log

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/postReducer.js
> +      console.log("Like success");
Okay you should check the issue above in the whole file.. :)

2020-04-27 10:04 UTC, schettn commented on src/store/reducers/userReducer.js
>        console.log("Get user info success");
add newline or remove the console log. Check for this issue in the whole file.

2020-04-27 12:19 UTC, pinterid approved these changes
Looks good to merge after the changes @schettn requested are implemented.

2020-04-27 12:45 UTC, Aichnerc commented on src/components/molecules/modals/AboutUs/index.jsx
> +  toggle = (nr) => () => {
This is a curried function, which does not make sense in this case. It has been removed and converted to a regular function as you requested.

2020-04-27 12:46 UTC, Aichnerc commented on src/components/organisms/ZombieList/index.jsx
> +    };
This entire function was useless in this component and has been removed.

2020-04-27 12:49 UTC, Aichnerc commented on src/store/actions/postActions.js
> +        dispatch({ type: "CREATION_SUCCESS", newPost });
The entire file has been removed, once it was no longer in use.

2020-04-27 12:56 UTC, schettn approved these changes
LGTM!

2020-04-27 13:01 UTC, merged