Add profile 1
aichner/KISy-Firebase pull request #3
Opened 2020-04-29 16:45 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, the design part of a website is not important enough.
- Currently, customers can not log in to see their analysis.
- Currently, the Result Chart (Signet) does not look like the website and is unfit for use in physical analysis.
- Currently, the greeting is only fitting for existing members. (Welcome back)
- Currently, there is much content in the ProfilePage, which does not really apply to our Atomic Design philosophy.

**What is the new behavior (if this is a feature change)?**
- The weight of the design part of a website has been increased.
- Customers can now log in to see their analysis.
- Customers can now see details regarding their analysis.
- The design of the Result Chart (Signet) has been improved to fit the website.
- The greeting has been improved to fit all new users as well. (Welcome)
- The ProfilePage has been split up in multiple lower-level components to please the Atomic Design gods.

**Other information**:
- The version has been updated to v1.3.0.

2020-04-29 16:55 UTC, Aichnerc reviewed
Looks good. But I could... be... preoccupied.

2020-04-29 17:02 UTC, schettn requested changes
almost-but-not-quite

2020-04-29 17:02 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.error("Could not upgrade", action.err);
add newline or remove console.log

2020-04-29 17:02 UTC, schettn commented on src/store/reducers/authReducer.js
> +      console.error("Could not get zombies", action.err);
add newline or remove console.log

2020-04-29 17:13 UTC, LucaAllmaier approved these changes
Looks good.

2020-04-29 17:16 UTC, pinterid commented on src/components/molecules/Services/index.jsx
> +    //this.getAnalytics();
Remove this comment or add a newline after it.

2020-04-29 17:22 UTC, pinterid commented on src/components/organisms/ZombieList/zombie.scss
> -
Missing new line.

2020-04-29 17:26 UTC, pinterid requested changes
Should be ok to merge after a few changes.

2020-04-29 17:51 UTC, sweggerat approved these changes
looks good

2020-04-29 18:46 UTC, schettn approved these changes
LGTM!

2020-04-29 18:47 UTC, pinterid approved these changes
Looks good to merge.

2020-04-30 09:05 UTC, kleberbaum reviewed
lmao xD

2020-04-30 09:05 UTC, kleberbaum commented on src/components/molecules/Services/index.jsx
> +                    </MDBAlert>
warning: Deine Website wurde nicht von uns erstellt. xD

2020-04-30 09:06 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-04-30 09:07 UTC, merged