Add add-messages-1 to master
aichner/KISy-Firebase pull request #5
Opened 2020-05-07 15:46 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, coaches can not view messages or see requests for analysis.
- Currently, the `zombie` view is very cluttered and you can harldy distinguish between open and closed `zombies`.
- Currently, there is no version number.

**What is the new behavior (if this is a feature change)?**
- Coaches can now view messsenges and see requests for analysis. This includes a wide range of features, like marking one as closed.
- `Zombies` marked done now have a green `ResultChart`.
- The version nummber is now logged via console.

**Other information**:
- The version has been updated. (Minor)

2020-05-07 15:57 UTC, sweggerat approved these changes
looks good

2020-05-07 17:32 UTC, LucaAllmaier approved these changes
Looks good to me.

2020-05-07 20:18 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-05-07 20:18 UTC, kleberbaum commented on src/components/molecules/Footer/index.jsx
> +import { MDBFooter,MDBContainer, MDBIcon } from "mdbreact";
missing whitespace after comma.

2020-05-07 20:18 UTC, kleberbaum commented on src/components/organisms/Requests/index.jsx
> +        this.setState({ sync: false });
Please check indentation.

2020-05-07 20:18 UTC, kleberbaum commented on src/components/organisms/Requests/index.jsx
> +        contact.data.length > 0 ? (
Please check indentation.

2020-05-07 20:23 UTC, Aichnerc commented on src/components/organisms/Requests/index.jsx
> +        contact.data.length > 0 ? (
Indentation is okay.

2020-05-07 20:34 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-05-07 22:15 UTC, schettn requested changes
Should be ok but please check my comments.

2020-05-07 22:15 UTC, schettn commented on src/components/molecules/charts/ResultChart/index.jsx
>        let labels, data;
add newline

2020-05-07 22:15 UTC, schettn commented on src/components/organisms/FormCat/index.jsx
> +    const { catDetails } = this.props;
add newline

2020-05-08 08:02 UTC, schettn approved these changes
LGTM! 🦺

2020-05-08 08:02 UTC, merged